# Generated by Django 5.2.1 on 2025-06-12 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=150, verbose_name="Наименование"),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.IntegerField(verbose_name="Цена"),
        ),
    ]
